"""crear tablas iniciales

Revision ID: 47323616cee9
Revises: 
Create Date: 2026-03-17 17:40:49.208000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47323616cee9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jugadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('dni', sa.String(), nullable=True),
    sa.Column('posicion', sa.Enum('PILAR_IZQUIERDO', 'HOOKER', 'PILAR_DERECHO', 'SEGUNDA_LINEA', 'FLANKER', 'OCTAVO', 'MEDIO_SCRUM', 'APERTURA', 'CENTRO', 'ALA', 'FULLBACK', name='posicionjugador'), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('peso_kg', sa.Float(), nullable=True),
    sa.Column('altura_cm', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVO', 'LESIONADO', 'SUSPENDIDO', 'INACTIVO', name='estadojugador'), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_index(op.f('ix_jugadores_id'), 'jugadores', ['id'], unique=False)
    op.create_table('planteles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('temporada', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_planteles_id'), 'planteles', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('ADMIN', 'ENTRENADOR', 'MEDICO', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('lesiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('tipo_lesion', sa.String(), nullable=False),
    sa.Column('zona_corporal', sa.String(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('gravedad', sa.Enum('LEVE', 'MODERADA', 'GRAVE', name='gravedadlesion'), nullable=False),
    sa.Column('diagnostico', sa.Text(), nullable=True),
    sa.Column('tratamiento', sa.Text(), nullable=True),
    sa.Column('dias_recuperacion_estimados', sa.Integer(), nullable=True),
    sa.Column('estado', sa.Enum('ACTIVA', 'EN_RECUPERACION', 'ALTA_MEDICA', name='estadolesion'), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lesiones_id'), 'lesiones', ['id'], unique=False)
    op.create_table('partidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rival', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('torneo', sa.String(), nullable=True),
    sa.Column('condicion', sa.Enum('LOCAL', 'VISITANTE', name='condicionpartido'), nullable=False),
    sa.Column('puntos_favor', sa.Integer(), nullable=True),
    sa.Column('puntos_contra', sa.Integer(), nullable=True),
    sa.Column('plantel_id', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['plantel_id'], ['planteles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_partidos_id'), 'partidos', ['id'], unique=False)
    op.create_table('plantel_jugadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plantel_id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_ingreso', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['plantel_id'], ['planteles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantel_jugadores_id'), 'plantel_jugadores', ['id'], unique=False)
    op.create_table('alineaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('numero_camiseta', sa.Integer(), nullable=True),
    sa.Column('es_titular', sa.Boolean(), nullable=True),
    sa.Column('ingreso_minuto', sa.Integer(), nullable=True),
    sa.Column('salida_minuto', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alineaciones_id'), 'alineaciones', ['id'], unique=False)
    op.create_table('estadisticas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('tries', sa.Integer(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('conversiones', sa.Integer(), nullable=True),
    sa.Column('penales_convertidos', sa.Integer(), nullable=True),
    sa.Column('penales_errados', sa.Integer(), nullable=True),
    sa.Column('drops', sa.Integer(), nullable=True),
    sa.Column('tarjetas_amarillas', sa.Integer(), nullable=True),
    sa.Column('tarjetas_rojas', sa.Integer(), nullable=True),
    sa.Column('scrums_ganados', sa.Integer(), nullable=True),
    sa.Column('lineouts_ganados', sa.Integer(), nullable=True),
    sa.Column('penales_cometidos', sa.Integer(), nullable=True),
    sa.Column('penales_recibidos', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estadisticas_id'), 'estadisticas', ['id'], unique=False)
    op.create_table('penales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('partido_id', sa.Integer(), nullable=False),
    sa.Column('jugador_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('OFFSIDE', 'TACKLE_ALTO', 'NO_RELEASE', 'HOLDING_ON', 'SIDE_ENTRY', 'COLLAPSING_SCRUM', 'NOT_ROLLING_AWAY', 'INFRACCION_LINEOUT', 'JUEGO_PELIGROSO', 'INCONDUCTA', 'REPETICION_INFRACCIONES', 'OTRO', name='tipopenal'), nullable=False),
    sa.Column('minuto', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['jugador_id'], ['jugadores.id'], ),
    sa.ForeignKeyConstraint(['partido_id'], ['partidos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penales_id'), 'penales', ['id'], unique=False)
    op.create_table('seguimientos_lesion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesion_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('nota', sa.Text(), nullable=False),
    sa.Column('creado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['lesion_id'], ['lesiones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seguimientos_lesion_id'), 'seguimientos_lesion', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seguimientos_lesion_id'), table_name='seguimientos_lesion')
    op.drop_table('seguimientos_lesion')
    op.drop_index(op.f('ix_penales_id'), table_name='penales')
    op.drop_table('penales')
    op.drop_index(op.f('ix_estadisticas_id'), table_name='estadisticas')
    op.drop_table('estadisticas')
    op.drop_index(op.f('ix_alineaciones_id'), table_name='alineaciones')
    op.drop_table('alineaciones')
    op.drop_index(op.f('ix_plantel_jugadores_id'), table_name='plantel_jugadores')
    op.drop_table('plantel_jugadores')
    op.drop_index(op.f('ix_partidos_id'), table_name='partidos')
    op.drop_table('partidos')
    op.drop_index(op.f('ix_lesiones_id'), table_name='lesiones')
    op.drop_table('lesiones')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_planteles_id'), table_name='planteles')
    op.drop_table('planteles')
    op.drop_index(op.f('ix_jugadores_id'), table_name='jugadores')
    op.drop_table('jugadores')
    # ### end Alembic commands ###
